---
# List of flatpak applications to manage (available on all architectures)
flatpaks_common:
  - com.dec05eba.gpu_screen_recorder
  - com.github.rajsolai.textsnatcher
  - com.github.tchx84.Flatseal
  - com.github.wwmm.easyeffects
  - com.jeffser.Alpaca
  - com.raggesilver.BlackBox
  - de.haeckerfelix.Shortwave
  - hu.irl.cameractrls
  - io.missioncenter.MissionCenter
  - io.podman_desktop.PodmanDesktop
  - md.obsidian.Obsidian
  - org.gnome.Calculator
  - org.gnome.gitlab.somas.Apostrophe
  - org.kde.kweather
  - org.videolan.VLC
  - tv.kodi.Kodi

# x86_64 only flatpaks
flatpaks_x86_64:
  - com.github.marktext.marktext
  - com.slack.Slack

# aarch64 only flatpaks
flatpaks_aarch64: []

# Combined list based on architecture
flatpaks: "{{ flatpaks_common + (flatpaks_x86_64 if ansible_facts['architecture'] == 'x86_64' else flatpaks_aarch64) }}"
