---
- name: Inception - full environment setup
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - shanemcd.toolbox.oh_my_zsh
    - shanemcd.toolbox.dotfiles
    - shanemcd.toolbox.flatpaks
    - shanemcd.toolbox.fonts
    - shanemcd.toolbox.emacs
