---
fedora_iso_version: "latest"
fedora_iso_arch_map:
  x86_64: x86_64
  arm64: aarch64
fedora_iso_architecture: "{{ ansible_architecture }}"
fedora_iso_variant: "Everything"
fedora_iso_build_context: "{{ playbook_dir }}/.generated"
fedora_iso_cleanup: false  # Whether to delete the temporary directory created for storing the downloaded ISO and rendered kickstart
fedora_iso_force: false
fedora_releases_json_url: "https://getfedora.org/releases.json"
fedora_iso_kickstart_shutdown_command: "reboot"
container_runtime: "podman"  # Container runtime to use: "podman" or "docker"
fedora_iso_ostree_image: "quay.io/shanemcd/mybox"
fedora_iso_ostree_tag: "latest-{{ fedora_iso_arch_map[fedora_iso_architecture] }}"
