---
# Chezmoi repository to clone
dotfiles_repo: "git@github.com:shanemcd/dotfiles.git"

# Chezmoi source directory
dotfiles_source_dir: "{{ ansible_facts['env']['HOME'] }}/.local/share/chezmoi"

# Whether to run chezmoi apply after init
dotfiles_apply: true

# Whether to run the setup-secrets.sh script if it exists
dotfiles_setup_secrets: true
